#include "RCC_STM32_LIB.h"


void RCC_Enable_For_GPIO_ADC_SPI_DMA(void)
{
    /* GPIOA, GPIOB */
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN;

    /* DMA2 for ADC1 */
    RCC->AHB1ENR |= RCC_AHB1ENR_DMA2EN;

    /* ADC1 + SPI1 on APB2 */
    RCC->APB2ENR |= RCC_APB2ENR_ADC1EN | RCC_APB2ENR_SPI1EN;
}